### ISSUE TITLE
azp: vscode ext collect all errors of independent subtemplates at the same time

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#274]
Currently only on template file error path is shown in the error message

**Comment by bryanbcook** [comment]
I think it would make sense to adapt/wrap the results of the template expansion so that we aren't allowing Exceptions from the .NET space to bubble up into the extension.

eg

```json
{
  "errorMessages": [
      {
          "file": "<path>",
          "pos": { "line": 1, "col": 2 },
          "message": "parameter is missing..."
      }
  ],
  "files": [
      {  "repo": "owner/repo@ref", "file": "path" }
  ]
  "finalYaml": "// encoded yaml",
}
```

**Comment by bryanbcook** [comment]
> ...and exact file locations...

My mistake, I thought the `TemplateValidationException` had the FileId, Line and Column as properties. These details are captured in the error message and [calculated here](https://github.com/ChristopherHX/runner.server/blob/0b83f0eaa83214b9ae4a9fd37b30f82b733fe375/src/Sdk/DTObjectTemplating/ObjectTemplating/TemplateContext.cs#L130C1-L146C10). Reading the file details from the Exception.Message instead of the stack trace is less likely to present issues.
