### ISSUE TITLE
LocalCheckout does not copy .git repository folder

### ISSUE THREAD

**Issue by JustinGrote** [ChristopherHX/runner.server#34]
**Describe the bug**
`actions/checkout` will do a full git clone of the repository, including the .git repository. The custom localcheckout does not. Some actions like ones that compute version from git commit messages (my example here) fail because that doesn't exist.

![image](https://user-images.githubusercontent.com/15258962/117888633-37a70380-b267-11eb-92de-dff1359488ee.png)

If this is not desired by default, at least add a switch to enable it to occur with the localcheckout so that these kinds of tasks can be accurately tested.

**Comment by ChristopherHX** [comment]
Should be fixed after merging my patch.

What if you don't have a `.git` dir in your checkout? This happens if you use github worktree or other special functions.

I thought about using git stash, then clone over http if both src and dest have git available.

`git stash create`

`git stash store ....`

Clone the stash over http

`git stash drop...`

I currently don't handle symlinks, may lead to problems.



actions/checkout has a fallback to download a zip of the repo without .git dir.

**Comment by JustinGrote** [comment]
@ChristopherHX if the .git doesn't exist and you've specified a sub workdir, I don't think it should try to go "find" it.

Obviously I think the goal should be to mirror actions/checkout behavior. I know that it has that REST API fallback but that's only if git is not present on the runner and it currently would be in everything except a local runner I think, so a check or command line switch would probably be sufficient if you want to replicate this behavior.

**Comment by ChristopherHX** [comment]
I mean, it shall work not only for a basic git clone.
Now I blindly copy the .git dir again, which isn't a long term solution.
Also git hooks miss the executable permissions, because windows drops the executable bit.

.git dirs are implementation specfic, copying fails in at least these cases
- `.git` is a file with a git symlink (`git rev-parse --git-dir` resolves the path, this leads to point 2)
- `.git` contains other git symlinks which points to another .git dir 
  - copying that would invalidate the head ref and checked out branch

The only ~~save~~ way to copy a .git dir (I know about) is to use `git clone path/to/repo --bare` (shallow clone?) then copy the temp folder.
Or use git clone to clone the repo via http(s) into the runner.

**Comment by JustinGrote** [comment]
@ChristopherHX tested with latest build, working well! Only thing I would think is maybe suppress the git individual file copy messages, they get pretty verbose:
![image](https://user-images.githubusercontent.com/15258962/118135205-98455600-b3b7-11eb-929c-759ec9ee982c.png)

**Comment by ChristopherHX** [comment]
Yes `console.log` should be replaced with `core.debug`: https://github.com/ChristopherHX/runner.server/blob/0e189e2acb26ef742e07a87497ffd5c633f4eafb/src/Runner.Server/localcheckout/index.js#L65
Adding `-s ACTIONS_STEP_DEBUG=true` hopefully would still show them, to debug issues of localcheckout
