### ISSUE TITLE
actions/checkout fails with "|##[error]Input required and not supplied: token"

### ISSUE THREAD

**Issue by acotty** [ChristopherHX/runner.server#77]
**Describe the bug**
Using the Github server you can checkout third party repositories, but using the the .\bin\Runner.Client.exe checking out third party repos fails.

**To Reproduce**
1. When I run the following command:
 .\bin\Runner.Client.exe --workflow .github\workflows\Windows-continuous-integration.yml --event push --payload CB_test.json -P 3. I see the following error:
```
|##[error]Input required and not supplied: token
[Windows Integration Builds / continuous-integration] Failed: Checkout wxWidget 3.1.6 source
[Windows Integration Builds / continuous-integration] Running: Post Checkout wxWidget 3.1.6 source

```
**Expected behavior**
The report should be checked out as it is a public repo and as such does not require any token. I am not the owner or dev of wxWidgets.

## Runner Version and Platform
$ .\bin\Runner.Client.exe --version
3.8.0

OS info:
  Windows 10  21H2 patched up to the latest from earlier this week (16-MAy-2022)
  

## What's not working?
The following fails in the workflow file using the .\bin\Runner.Client.exe , but works on gitub.com :

```
      - name: Checkout wxWidget 3.1.6 source
        uses: actions/checkout@v3
        with:
          repository: 'wxWidgets/wxWidgets'
          path: 'wxWidgets-3.1.6'

```
## Job Log Output
Attached is the non verbose log and a verbose log and the workflow file I am using. My public repo is https://github.com/acotty/CodeBlocks_Unofficial_Testing , but it may not have the latest workflow file as I am trying to get it fully working.

## Runner and Worker's Diagnostic Logs
I cannot find any *runner*.log files

## Additional Info 
I tried with --remote-checkout and the checkout for acotty/CodeBlocks_Unofficial_Testing failed with the same error.

The CB_test.json is:
{
    "inputs": {
        "x": "Hello World from event"
    }
}

[ZZ_Fail_Verbose.txt](https://github.com/ChristopherHX/runner.server/files/8735250/ZZ_Fail_Verbose.txt)
[ZZ_Fail.txt](https://github.com/ChristopherHX/runner.server/files/8735251/ZZ_Fail.txt)
[Windows-continuous-integration.yml.txt](https://github.com/ChristopherHX/runner.server/files/8735253/Windows-continuous-integration.yml.txt)

**Comment by ChristopherHX** [comment]
The problem is that the official `actions/checkout` has a implicit required input `token` with default value ` ${{github.token}}`, which is intentional empty since most actions work without any token.
I suggest to create a [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
Then run `.\bin\Runner.Client.exe -s GITHUB_TOKEN` and provide your token.
You can also create a `.secrets` file in your repo with the following content
```
GITHUB_TOKEN=replaceThisTextWithYourPersonalAccessToken
```

_This program is unable to generate a GITHUB_TOKEN automatically unless you configure `Runner.Server` as a github app for your account or organization_, github actions is a github app and can create a token automatically.

There are more actions with a similar behavior like `actions/github-script`. 

Probably it is possible to link this issue if the token parameter of actions/checkout is empty and you are checking out a different repository.

**Comment by acotty** [comment]
Thanks very much for the info. It works and am now getting the same failure as on github.com due to environmental issues that I need to solve.

Some feedback on the solution is that if you use the `.\bin\Runner.Client.exe -s GITHUB_TOKEN`  option then you need to press enter as the app stops near the the beginning of the process when it displays the token, but using the .secrets file does not require you to press enter or do anything.

I would suggest adding it somewhere to the readme.md file so other people do not fall into the same hole.
